Repository jbarnes850/agent-arcade, pull requests merged in 2025-02, with the labels that each got.

#1 feat: Enhance CLI and documentation for Agent Arcade
  README.md
  cli/__init__.py
  cli/games/__init__.py
  cli/games/base.py
  cli/games/pong/__init__.py
  cli/games/pong/commands.py
  cli/games/pong/game.py
  cli/games/pong/pong_arcade.py
  cli/games/space invaders/space_invaders_arcade.py
  cli/games/space_invaders/__init__.py
  cli/games/space_invaders/game.py
  cli/main.py
  docs/getting-started.md
  install.sh
  setup.py
Labels: bug, enhancement

#7 Updated installation script to handle permission issues when installing NEAR CLI.
  install.sh
Labels: bug

#13 feat: Enhance AutoROM and ALE-py ROM installation process
  gpu_install.sh
  install.sh
Labels: documentation, enhancement

#14 chore: Simplify .gitignore model file exclusions
  .gitignore
  models/README.md
  models/pong/config.yaml
  models/river_raid/config.yaml
  models/space_invaders/config.yaml
Labels: enhancement

#17 Feat smart contract
  contract/Cargo.lock
  contract/Cargo.toml
  contract/README.md
  contract/src/lib.rs
  contract/src/tests/integration.rs
  contract/src/tests/upgrade_tests.rs
  contract/src/types/config.rs
  contract/src/types/mod.rs
  contract/src/types/stake.rs
  contract/src/types/state.rs
  contract/src/upgrade.rs
  contract/target/.rustc_info.json
  contract/target/wasm32-unknown-unknown/release/.fingerprint/agent-arcade-b3da2b68d438100b/dep-lib-agent_arcade
  contract/target/wasm32-unknown-unknown/release/.fingerprint/agent-arcade-b3da2b68d438100b/lib-agent_arcade
  contract/target/wasm32-unknown-unknown/release/.fingerprint/agent-arcade-b3da2b68d438100b/lib-agent_arcade.json
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde-06720da5dce1037c/run-build-script-build-script-build
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde-06720da5dce1037c/run-build-script-build-script-build.json
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde-114e20902f40fd36/lib-serde
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde-114e20902f40fd36/lib-serde.json
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde_json-cdde4cb7f5cfc9b8/lib-serde_json
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde_json-cdde4cb7f5cfc9b8/lib-serde_json.json
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde_json-da41ce65de2a7b7c/run-build-script-build-script-build
  contract/target/wasm32-unknown-unknown/release/.fingerprint/serde_json-da41ce65de2a7b7c/run-build-script-build-script-build.json
  contract/target/wasm32-unknown-unknown/release/agent_arcade.d
  contract/target/wasm32-unknown-unknown/release/agent_arcade.wasm
  contract/target/wasm32-unknown-unknown/release/deps/agent_arcade.d
  contract/target/wasm32-unknown-unknown/release/deps/agent_arcade.wasm
  docs/README.md
  docs/deployment-guide.md
  docs/getting-started.md
  install.sh
Labels: bug, documentation, enhancement

#24 Secure Stake Submission System with Verification Tokens
  cli/core/evaluation.py
  cli/core/wallet.py
  cli/games/pong/game.py
  cli/games/riverraid/game.py
  cli/games/space_invaders/game.py
  cli/main.py
  docs/README.md
  docs/adding-games.md
  docs/cli-reference.md
  docs/competition-guide.md
  docs/deployment-guide.md
  docs/getting-started.md
  docs/training-guide.md
Labels: bug, documentation, enhancement
